
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const databaseUrl = process.env.DATABASE_URL;
const hasPostgresUrl = Boolean(
  databaseUrl &&
  (databaseUrl.startsWith("postgresql://")
    || databaseUrl.startsWith("postgres://")
    || databaseUrl.startsWith("prisma+postgres://"))
);
const resolvedDatabaseUrl = hasPostgresUrl
  ? (databaseUrl as string)
  : "postgresql://placeholder:placeholder@localhost:5432/placeholder?schema=public";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // `prisma generate` does not need a live database URL.
    // Use a harmless fallback so CI/Vercel installs don't fail before envs are set.
    url: resolvedDatabaseUrl,
  },
});
