import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const dataDir = path.join(process.cwd(), 'data');
const dataFile = path.join(dataDir, 'db.json');
const timestamp = new Date().toISOString();

const seed = {
  stories: [
    {
      id: 'story-demo-merdeka',
      title: 'The Debate at Merdeka Hall',
      description: 'A short branching political drama about transit, public trust, and who pays for progress.',
      defaultMusicTrackId: 'music-merdeka-theme',
      createdAt: timestamp,
      updatedAt: timestamp,
    },
  ],
  characters: [
    {
      id: 'char-amira',
      name: 'Amira Rahman',
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'char-bima',
      name: 'Bima Hartono',
      createdAt: timestamp,
      updatedAt: timestamp,
    },
  ],
  characterSprites: [
    {
      id: 'char-amira-default',
      characterId: 'char-amira',
      label: 'Default',
      imageUrl: '/demo/amira-portrait.svg',
      isDefault: true,
      sortOrder: 0,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'char-amira-smile',
      characterId: 'char-amira',
      label: 'Smile',
      imageUrl: '/demo/amira-smile.svg',
      isDefault: false,
      sortOrder: 1,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'char-amira-determined',
      characterId: 'char-amira',
      label: 'Determined',
      imageUrl: '/demo/amira-determined.svg',
      isDefault: false,
      sortOrder: 2,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'char-bima-default',
      characterId: 'char-bima',
      label: 'Default',
      imageUrl: '/demo/bima-portrait.svg',
      isDefault: true,
      sortOrder: 0,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'char-bima-concerned',
      characterId: 'char-bima',
      label: 'Concerned',
      imageUrl: '/demo/bima-concerned.svg',
      isDefault: false,
      sortOrder: 1,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'char-bima-rally',
      characterId: 'char-bima',
      label: 'Rally',
      imageUrl: '/demo/bima-rally.svg',
      isDefault: false,
      sortOrder: 2,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
  ],
  backgrounds: [
    {
      id: 'bg-merdeka-hall',
      name: 'Merdeka Hall',
      imageUrl: '/demo/hall-bg.svg',
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'bg-debate-stage',
      name: 'Debate Stage',
      imageUrl: '/demo/debate-bg.svg',
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'bg-community-floor',
      name: 'Community Floor',
      imageUrl: '/demo/community-bg.svg',
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'bg-night-closing',
      name: 'Night Closing',
      imageUrl: '/demo/night-bg.svg',
      createdAt: timestamp,
      updatedAt: timestamp,
    },
  ],
  musicTracks: [
    {
      id: 'music-merdeka-theme',
      name: 'Merdeka Theme',
      audioUrl: '/demo/merdeka-theme.wav',
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'music-rally-shift',
      name: 'Rally Shift',
      audioUrl: '/demo/rally-shift.wav',
      createdAt: timestamp,
      updatedAt: timestamp,
    },
  ],
  nodes: [
    {
      id: 'node-opening',
      storyId: 'story-demo-merdeka',
      characterId: null,
      characterSpriteId: null,
      backgroundId: 'bg-merdeka-hall',
      musicTrackId: null,
      editorDepth: 0,
      editorOrder: 0,
      text: 'Rain presses against the glass roof of Merdeka Hall as students, journalists, and city workers fill the chamber. Tonight, your campaign will either earn trust or lose the room.',
      audioUrl: null,
      isStartNode: true,
      isEndNode: false,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'node-amira-pitch',
      storyId: 'story-demo-merdeka',
      characterId: 'char-amira',
      characterSpriteId: null,
      backgroundId: 'bg-debate-stage',
      musicTrackId: null,
      editorDepth: 1,
      editorOrder: 0,
      text: 'Amira straightens a stack of notes. "We can cut commute times in half with an electric tram loop, but only if we protect the neighborhoods it passes through."',
      audioUrl: null,
      isStartNode: false,
      isEndNode: false,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'node-bima-pushback',
      storyId: 'story-demo-merdeka',
      characterId: 'char-bima',
      characterSpriteId: 'char-bima-concerned',
      backgroundId: 'bg-debate-stage',
      musicTrackId: 'music-rally-shift',
      editorDepth: 1,
      editorOrder: 1,
      text: 'Bima leans into the microphone. "People want relief now. Freeze fares, pause the construction, and stop asking working families to gamble on a promise."',
      audioUrl: null,
      isStartNode: false,
      isEndNode: false,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'node-community-route',
      storyId: 'story-demo-merdeka',
      characterId: 'char-amira',
      characterSpriteId: 'char-amira-smile',
      backgroundId: 'bg-community-floor',
      musicTrackId: null,
      editorDepth: 2,
      editorOrder: 0,
      text: 'You back a neighborhood-first plan: phased construction, rent protections near stations, and a citizen oversight board. The crowd softens. Several union leaders begin taking notes.',
      audioUrl: null,
      isStartNode: false,
      isEndNode: false,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'node-populist-route',
      storyId: 'story-demo-merdeka',
      characterId: 'char-bima',
      characterSpriteId: 'char-bima-rally',
      backgroundId: 'bg-community-floor',
      musicTrackId: 'music-rally-shift',
      editorDepth: 2,
      editorOrder: 1,
      text: 'You endorse a fare freeze with no replacement funding. The applause is loud, but a transport analyst in the front row whispers that the buses will start failing within months.',
      audioUrl: null,
      isStartNode: false,
      isEndNode: false,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'node-reform-ending',
      storyId: 'story-demo-merdeka',
      characterId: 'char-amira',
      characterSpriteId: 'char-amira-determined',
      backgroundId: 'bg-night-closing',
      musicTrackId: 'music-merdeka-theme',
      editorDepth: 3,
      editorOrder: 0,
      text: 'By midnight, the headline reads: "Candidate Trades Speed for Trust, Wins the Room." The plan is slower, harder, and politically expensive, but people believe it belongs to them.',
      audioUrl: null,
      isStartNode: false,
      isEndNode: true,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'node-collapse-ending',
      storyId: 'story-demo-merdeka',
      characterId: 'char-bima',
      characterSpriteId: 'char-bima-concerned',
      backgroundId: 'bg-night-closing',
      musicTrackId: 'music-rally-shift',
      editorDepth: 3,
      editorOrder: 1,
      text: 'Three weeks later the temporary fare freeze collapses under debt pressure. Your rally clips still trend online, but riders are angrier than before and trust is harder to rebuild.',
      audioUrl: null,
      isStartNode: false,
      isEndNode: true,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
  ],
  choices: [
    {
      id: 'choice-opening-1',
      nodeId: 'node-opening',
      targetNodeId: 'node-amira-pitch',
      text: 'Open with an ambitious infrastructure case.',
      scoreImpact: 1,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'choice-opening-2',
      nodeId: 'node-opening',
      targetNodeId: 'node-bima-pushback',
      text: 'Open with immediate cost-of-living relief.',
      scoreImpact: 0,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'choice-amira-1',
      nodeId: 'node-amira-pitch',
      targetNodeId: 'node-community-route',
      text: 'Promise rent protections and public oversight.',
      scoreImpact: 3,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'choice-amira-2',
      nodeId: 'node-amira-pitch',
      targetNodeId: 'node-populist-route',
      text: 'Cut corners and promise the tram will pay for itself.',
      scoreImpact: -2,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'choice-bima-1',
      nodeId: 'node-bima-pushback',
      targetNodeId: 'node-community-route',
      text: 'Shift to a funded compromise before the room turns.',
      scoreImpact: 2,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'choice-bima-2',
      nodeId: 'node-bima-pushback',
      targetNodeId: 'node-populist-route',
      text: 'Double down on a crowd-pleasing freeze.',
      scoreImpact: -3,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'choice-community-1',
      nodeId: 'node-community-route',
      targetNodeId: 'node-reform-ending',
      text: 'Invite civic groups to co-sign the plan.',
      scoreImpact: 2,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'choice-populist-1',
      nodeId: 'node-populist-route',
      targetNodeId: 'node-collapse-ending',
      text: 'Run with the slogan and hope the numbers work later.',
      scoreImpact: -2,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
  ],
  playerScores: [],
  siteSettings: {
    publicLocale: 'id',
  },
};

await mkdir(dataDir, { recursive: true });
await writeFile(dataFile, JSON.stringify(seed, null, 2));
console.log(`Wrote demo database to ${dataFile}`);
