import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const dataDir = path.join(process.cwd(), 'data');
const dataFile = path.join(dataDir, 'db.json');
const timestamp = new Date().toISOString();

const seed = {
  stories: [
    {
      id: 'story-demo-merdeka',
      title: 'The Debate at Merdeka Hall',
      description: 'A short branching political drama about transit, public trust, and who pays for progress.',
      createdAt: timestamp,
      updatedAt: timestamp,
    },
  ],
  characters: [
    {
      id: 'char-amira',
      name: 'Amira Rahman',
      spriteImageUrl: '/demo/amira-portrait.svg',
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'char-bima',
      name: 'Bima Hartono',
      spriteImageUrl: '/demo/bima-portrait.svg',
      createdAt: timestamp,
      updatedAt: timestamp,
    },
  ],
  nodes: [
    {
      id: 'node-opening',
      storyId: 'story-demo-merdeka',
      characterId: null,
      text: 'Rain presses against the glass roof of Merdeka Hall as students, journalists, and city workers fill the chamber. Tonight, your campaign will either earn trust or lose the room.',
      backgroundImageUrl: '/demo/hall-bg.svg',
      audioUrl: null,
      isStartNode: true,
      isEndNode: false,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'node-amira-pitch',
      storyId: 'story-demo-merdeka',
      characterId: 'char-amira',
      text: 'Amira straightens a stack of notes. "We can cut commute times in half with an electric tram loop, but only if we protect the neighborhoods it passes through."',
      backgroundImageUrl: '/demo/debate-bg.svg',
      audioUrl: null,
      isStartNode: false,
      isEndNode: false,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'node-bima-pushback',
      storyId: 'story-demo-merdeka',
      characterId: 'char-bima',
      text: 'Bima leans into the microphone. "People want relief now. Freeze fares, pause the construction, and stop asking working families to gamble on a promise."',
      backgroundImageUrl: '/demo/debate-bg.svg',
      audioUrl: null,
      isStartNode: false,
      isEndNode: false,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'node-community-route',
      storyId: 'story-demo-merdeka',
      characterId: 'char-amira',
      text: 'You back a neighborhood-first plan: phased construction, rent protections near stations, and a citizen oversight board. The crowd softens. Several union leaders begin taking notes.',
      backgroundImageUrl: '/demo/community-bg.svg',
      audioUrl: null,
      isStartNode: false,
      isEndNode: false,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'node-populist-route',
      storyId: 'story-demo-merdeka',
      characterId: 'char-bima',
      text: 'You endorse a fare freeze with no replacement funding. The applause is loud, but a transport analyst in the front row whispers that the buses will start failing within months.',
      backgroundImageUrl: '/demo/community-bg.svg',
      audioUrl: null,
      isStartNode: false,
      isEndNode: false,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'node-reform-ending',
      storyId: 'story-demo-merdeka',
      characterId: null,
      text: 'By midnight, the headline reads: "Candidate Trades Speed for Trust, Wins the Room." The plan is slower, harder, and politically expensive, but people believe it belongs to them.',
      backgroundImageUrl: '/demo/night-bg.svg',
      audioUrl: null,
      isStartNode: false,
      isEndNode: true,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'node-collapse-ending',
      storyId: 'story-demo-merdeka',
      characterId: null,
      text: 'Three weeks later the temporary fare freeze collapses under debt pressure. Your rally clips still trend online, but riders are angrier than before and trust is harder to rebuild.',
      backgroundImageUrl: '/demo/night-bg.svg',
      audioUrl: null,
      isStartNode: false,
      isEndNode: true,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
  ],
  choices: [
    {
      id: 'choice-opening-1',
      nodeId: 'node-opening',
      targetNodeId: 'node-amira-pitch',
      text: 'Open with an ambitious infrastructure case.',
      scoreImpact: 1,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'choice-opening-2',
      nodeId: 'node-opening',
      targetNodeId: 'node-bima-pushback',
      text: 'Open with immediate cost-of-living relief.',
      scoreImpact: 0,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'choice-amira-1',
      nodeId: 'node-amira-pitch',
      targetNodeId: 'node-community-route',
      text: 'Promise rent protections and public oversight.',
      scoreImpact: 3,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'choice-amira-2',
      nodeId: 'node-amira-pitch',
      targetNodeId: 'node-populist-route',
      text: 'Cut corners and promise the tram will pay for itself.',
      scoreImpact: -2,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'choice-bima-1',
      nodeId: 'node-bima-pushback',
      targetNodeId: 'node-community-route',
      text: 'Shift to a funded compromise before the room turns.',
      scoreImpact: 2,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'choice-bima-2',
      nodeId: 'node-bima-pushback',
      targetNodeId: 'node-populist-route',
      text: 'Double down on a crowd-pleasing freeze.',
      scoreImpact: -3,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'choice-community-1',
      nodeId: 'node-community-route',
      targetNodeId: 'node-reform-ending',
      text: 'Invite civic groups to co-sign the plan.',
      scoreImpact: 2,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'choice-populist-1',
      nodeId: 'node-populist-route',
      targetNodeId: 'node-collapse-ending',
      text: 'Run with the slogan and hope the numbers work later.',
      scoreImpact: -2,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
  ],
  playerScores: [],
};

await mkdir(dataDir, { recursive: true });
await writeFile(dataFile, JSON.stringify(seed, null, 2));
console.log(`Wrote demo database to ${dataFile}`);
